//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesTrack.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class plan_master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public plan_master()
        {
            this.plan_detail = new HashSet<plan_detail>();
        }
    
        public long PlanID { get; set; }
        public string PlanName { get; set; }
        public string PlanDescription { get; set; }
        public Nullable<double> PlanCost { get; set; }
        public Nullable<int> PlanValidity_Days { get; set; }
        public Nullable<int> AllowedUsers { get; set; }
        public Nullable<double> CostPerUser { get; set; }
        public Nullable<int> AllowedSalesPersons { get; set; }
        public Nullable<double> CostPerSalesperson { get; set; }
        public Nullable<int> AllowedBusinesses { get; set; }
        public Nullable<double> CostPerBusines { get; set; }
        public Nullable<int> AllowedGoals { get; set; }
        public Nullable<double> CostPerGoal { get; set; }
        public Nullable<int> AllowedProducts { get; set; }
        public Nullable<double> CostPerProduct { get; set; }
        public Nullable<System.DateTime> PlanExpiryDate { get; set; }
        public Nullable<bool> LetsCompaniesPickupThisPlan { get; set; }
        public Nullable<bool> SpecialPlan { get; set; }
        public Nullable<double> SetupFee { get; set; }
        public string SetupFeeDescription { get; set; }
        public Nullable<double> MinimumFee { get; set; }
        public Nullable<double> OtherFee { get; set; }
        public string OtherFeeDescription { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<plan_detail> plan_detail { get; set; }
    }
}
