//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesTrack.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class salesperson_business_mapping
    {
        public long SalesPersonBusinessID { get; set; }
        public Nullable<long> SalespersonID { get; set; }
        public Nullable<long> BusinessID { get; set; }
    
        public virtual business business { get; set; }
        public virtual salesperson salesperson { get; set; }
    }
}
