//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesTrack.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_role_mapping
    {
        public long mappingID { get; set; }
        public Nullable<long> userID { get; set; }
        public Nullable<long> RoleID { get; set; }
    
        public virtual user_roles user_roles { get; set; }
        public virtual user user { get; set; }
    }
}
