//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesTracker.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class salesperson
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public salesperson()
        {
            this.salesperson_business_mapping = new HashSet<salesperson_business_mapping>();
        }
    
        public long SalesPersonID { get; set; }
        public Nullable<long> UserID { get; set; }
        public string FirstNamt { get; set; }
        public string LastName { get; set; }
        public string Mobile1 { get; set; }
        public string Mobile2 { get; set; }
        public string workPhone { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string ZipCode { get; set; }
        public string Country { get; set; }
        public Nullable<long> UserProfileID { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<salesperson_business_mapping> salesperson_business_mapping { get; set; }
        public virtual user user { get; set; }
        public virtual user_profile user_profile { get; set; }
    }
}
