//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesTracker.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_permissions
    {
        public long PermissionID { get; set; }
        public Nullable<long> UserID { get; set; }
        public Nullable<long> FeatureID { get; set; }
    
        public virtual feature feature { get; set; }
        public virtual user user { get; set; }
    }
}
