# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SalesTrack' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod 'Alamofire', '~> 4.0'
pod 'IQKeyboardManagerSwift'
pod 'SwiftyJSON', '~> 4.0'
pod 'MBProgressHUD'
pod 'iOS-Slide-Menu', ‘1.5’
pod 'GoogleMaps'
pod 'GooglePlaces'

  # Pods for SalesTrack

end
